export const cameras = [{
        name: 'Xpedite NXT',
        imgSrc: './images/EOSR5.png',
        imgAlt: 'Expedite Next PSE Compound Bow',
        drawWeight: '60, 70, 80',
        drawLength: '24.5" - 30"',
        massWeight: '4.74 lbs',
        speed: '360 fps',
        axle2axle: '33"',
        level: 'advanced',
        category: 'hunting',
        type: 'compound',
        color: 'Black, Tan, First Light Fusion, Kuiu Verde, Mossy Oak Country, Realtree Edge, Kryptek Altitude',
        url: 'https://psearchery.com/xpedite-nxt/',
    },
    {
        name: 'Drive XL',
        imgSrc: './images/drivexl.png',
        imgAlt: 'Drive XL PSE Compound Bow',
        drawWeight: '60, 70',
        drawLength: '26.5 -32"',
        massWeight: '3.9 lbs',
        speed: '327-319 fps',
        axle2axle: '33"',
        level: 'advanced',
        category: 'hunting',
        type: 'compound',
        color: 'Mossy Oak Country, Kuiu Verde, Black',
        url: 'https://psearchery.com/drive-xl/',
    },
    {
        name: 'Drive SD',
        imgSrc: './images/drivesd.png',
        imgAlt: 'Drive SD PSE Compound Bow',
        drawWeight: '40, 50',
        drawLength: '22" - 25.5"',
        massWeight: '3.7 lbs',
        speed: '282 - 274 fps',
        axle2axle: '29.5"',
        level: 'beginner',
        category: 'hunting',
        type: 'compound',
        color: 'Mossy Oak Country, Kuiu Verde, Black',
        url: 'https://psearchery.com/drive-sd/',
    },
    {
        name: 'Citation',
        imgSrc: './images/citation.png',
        imgAlt: 'Citation PSE Compound Bow',
        drawWeight: '50, 60',
        drawLength: '28" - 33.5"',
        massWeight: '5.2 lbs',
        speed: '314 - 306 fps',
        axle2axle: '40"',
        level: 'Intermediate',
        category: 'competition',
        type: 'compound',
        color: 'White, Satin Mercury, Sky Blue, Platinum Titanium, Orange, Navy Blue, Good Vibes, Black, Black Cherry, American Flag',
        url: 'https://psearchery.com/citation/',
    },
    {
        name: 'Perform X',
        imgSrc: './images/performx.png',
        imgAlt: 'Perform X PSE Compound Bow',
        drawWeight: '50, 60',
        drawLength: '26.5" - 32"',
        massWeight: '5.2 lbs',
        speed: '332 - 324 fps',
        axle2axle: '40"',
        level: 'intermediate',
        category: 'competition',
        type: 'compound',
        color: 'American Flag, Good Vibrations, Black Cherry, White, Navy Blue, Black, Platinum Titanium, *Sky Blue, *Orange, *Satin Mercury, *Premium colors additional charge',
        url: 'https://psearchery.com/perform-x/',
    },
    {
        name: 'Perform-X 3D',
        imgSrc: './images/performx3d.png',
        imgAlt: 'Perform-X 3D PSE Compound Bow',
        drawWeight: '50, 60',
        drawLength: '25" - 30.5"',
        massWeight: '5 lbs',
        speed: '338-330 fps',
        axle2axle: '36"',
        level: 'advanced',
        category: 'competition',
        type: 'compound',
        color: 'American Flag, Good Vibrations, Black Cherry, Navy Blue, White, Black, Platinum Titanium, *Sky Blue, *Orange, *Satin Mercury. *Premium colors additional charge',
        url: 'https://psearchery.com/perform-x3d/',
    },  
    {
        name: 'Centrix LD',
        imgSrc: './images/centrixld.png',
        imgAlt: 'Centrix LD PSE Compound Bow',
        drawWeight: '50, 60',
        drawLength: '26.5" - 32"',
        massWeight: '3.9 lbs',
        speed: '327-319 fps',
        axle2axle: '33"',
        level: 'intermediate',
        category: 'competition',
        type: 'compound',
        color: 'Platinum Titanium, Purple, Rose Gold, Black Cherry, White',
        url: 'https://psearchery.com/centrixld/',
    },
    {
        name: 'Supra Focus XL LD',
        imgSrc: './images/suprafocusxlld.png',
        imgAlt: 'Supra Focus XL LD PSE Compound Bow',
        drawWeight: '50, 60',
        drawLength: '28" - 33.5"',
        massWeight: '5.3 lbs',
        speed: '312-304 fps',
        axle2axle: '40"',
        level: 'intermediate',
        category: 'competition',
        type: 'compound',
        color: 'American Flag, Good Vibrations, Black Cherry, White, Navy Blue, Black, Platinum Titanium, *Sky Blue, *Orange, *Satin Mercury, *Premium colors additional charge',
        url: 'https://psearchery.com/suprafocus-xl-ld/',
    },
    {
        name: 'Supra Focus',
        imgSrc: './images/suprafocus.png',
        imgAlt: 'Supra Focus PSE Compound Bow',
        drawWeight: '50, 60',
        drawLength: '26" - 31.5"',
        massWeight: '4.7 lbs',
        speed: '326-318 fps',
        axle2axle: '37"',
        level: 'advanced',
        category: 'competition',
        type: 'compound',
        color: 'American Flag, Good Vibrations, Black Cherry, White, Navy Blue, Black, Platinum Titanium, *Sky Blue, *Orange, *Satin Mercury, *Premium colors additional charge',
        url: 'https://psearchery.com/suprafocus/',
    },
    {
        name: 'Bandit NXT',
        imgSrc: './images/banditnxt.png',
        imgAlt: 'Bandit NXT PSE Compound Bow',
        drawWeight: '40, 50',
        drawLength: '20.5" - 26"',
        massWeight: '3.7 lbs',
        speed: '307 - 299 fps',
        axle2axle: '28"',
        level: 'beginner',
        category: 'competition',
        type: 'compound',
        color: 'Kuiu Verde, Mossy Oak Country, First Lite Fusion, RealTree Edge, Black, Tan',
        url: 'https://psearchery.com/bandit-nxt/',
    },
    {
        name: 'Evo NXT 33',
        imgSrc: './images/evonxt.png',
        imgAlt: 'Evo NXT 33 PSE Compound Bow',
        drawWeight: '50, 60, 65, 70, 80',
        drawLength: '26.5" - 31.5"',
        massWeight: '4.5 lbs',
        speed: '322 - 314 fps',
        axle2axle: '33"',
        level: 'beginner',
        category: 'competition',
        type: 'compound',
        color: 'Mossy Oak Country, Kuiu Verde, First Lite Fusion, RealTree Edge, Black, Tan',
        url: 'https://psearchery.com/evo-nxt-33/',
    },
    {
        name: 'Carbon Air Stealth Mach 1',
        imgSrc: './images/carbonairstealth.png',
        imgAlt: 'Carbon Air Stealth Mach 1 PSE Compound Bow',
        drawWeight: '50, 60, 65, 70, 80',
        drawLength: '25" - 30.5"',
        massWeight: '3.5 lbs',
        speed: '332 - 324 fps',
        axle2axle: '32"',
        level: 'beginner',
        category: 'hunting',
        type: 'compound',
        color: 'Black, Kuiu Verde, Mossy Oak Country, First Lite Fusion',
        url: 'https://psearchery.com/carbon-air-stealth-mach-1/',
    },
    {
        name: 'Prima',
        imgSrc: './images/prima.png',
        imgAlt: 'Prima Mathews PSE Compound Bow',
        drawWeight: '40, 50, 60',
        drawLength: '21.5" - 27.5"',
        massWeight: '3.93 lbs',
        speed: '321 fps',
        axle2axle: '30"',
        level: 'intermediate',
        category: 'hunting',
        type: 'compound',
        color: 'First Lite Specter, Under Armor, Realtree Edge, Green Ambush, Stone, Black, Optifade Subalpine, Optifade Elevated II',
        url: 'https://www.mathewsinc.com/product/prima/',
    },  
    {
        name: 'Monster Safari',
        imgSrc: './images/monstersafari.png',
        imgAlt: 'Monster Safari Mathews Compound Bow',
        drawWeight: '70, 85',
        drawLength: '25.5" - 31"',
        massWeight: '4.8 lbs',
        speed: '350 fps',
        axle2axle: '33',
        level: 'advanced',
        category: 'hunting',
        type: 'compound',
        color: 'Black',
        url: 'https://www.mathewsinc.com/product/monster-safari/',
    },  
    {
        name: 'Stoke',
        imgSrc: './images/stoke.png',
        imgAlt: 'Stoke Mathews Compound Bow',
        drawWeight: '40, 50, 60',
        drawLength: '21 - 27"',
        massWeight: '3.78 lbs',
        speed: '314 fps',
        axle2axle: '27.25"',
        level: 'beginner',
        category: 'hunting',
        type: 'compound',
        color: 'Black, Lost Camo XD, Stone',
        url: 'https://www.mathewsinc.com/product/stoke/',
    },  
    {
        name: 'Tactic',
        imgSrc: './images/tactic.png',
        imgAlt: 'Tactic Mathews Compound Bow',
        drawWeight: '50, 60, 70',
        drawLength: '23" - 30"',
        massWeight: '4.24 lbs',
        speed: 'up to 335 fps',
        axle2axle: '30.5"',
        level: 'intermediate',
        category: 'hunting',
        type: 'compound',
        color: 'Black, Realtree Edge',
        url: 'https://www.mathewsinc.com/product/tactic/',
    },  
    {
        name: 'Conquest 4',
        imgSrc: './images/conquest4.png',
        imgAlt: 'Conquest 4 Mathews Compound Bow',
        drawWeight: '40, 50, 60, 70',
        drawLength: '28" - 32"',
        massWeight: '4.4 lbs',
        speed: 'up to 310 fps',
        axle2axle: '40 5/8"',
        level: 'intermediate',
        category: 'competition',
        type: 'compound',
        color: 'Black',
        url: 'https://www.mathewsinc.com/product/conquest-4/',
    },  
    {
        name: 'TRX 36',
        imgSrc: './images/trx36.png',
        imgAlt: 'TRX 36 Mathews Compound Bow',
        drawWeight: '50, 60, 70',
        drawLength: '24" - 30.5"',
        massWeight: '4.66 lbs',
        speed: '334 fps',
        axle2axle: '36"',
        level: 'intermediate',
        category: 'competition',
        type: 'compound',
        color: 'Stone, Black, Blue, White, Red',
        url: 'https://www.mathewsinc.com/product/trx-36/',
    },  
    // need more intermediate hunting bows
    {
        name: 'SATORI 17 RISER',
        imgSrc: './images/satori17.png',
        imgAlt: 'SATORI 17 RISER Recurve Bow',
        drawWeight: 'Depends on the Limbs Purchased',
        drawLength: 'Riser Length - 17"',
        massWeight: '2.68 lbs',
        speed: 'n/a',
        axle2axle: '60"',
        level: 'intermediate',
        category: 'hunting',
        type: 'recurve',
        color: 'Black Out, Storm',
        url: 'https://hoyt.com/recurve-bows/satori-risers',
    },  
    {
        name: 'Samick Little Fox',
        imgSrc: './images/samick58.png',
        imgAlt: 'SAMICK LITTLE FOX Recurve Bow',
        drawWeight: '21-30 lbs',
        drawLength: 'n/a',
        massWeight: '3 lbs',
        speed: 'n/a',
        axle2axle: '58"',
        level: 'beginner',
        category: 'competition',
        type: 'recurve',
        color: 'White Oak, Dymondwood, and Maple',
        url: 'https://www.lancasterarchery.com/samick-little-fox-58-takedown-bow.html',
    },  
    {
        name: 'Scorpion',
        imgSrc: './images/scorpion.png',
        imgAlt: 'Scorpion Recurve Bos',
        drawWeight: '40, 45, 50, 55, 60 lbs',
        drawLength: 'n/a',
        massWeight: '2 lbs 3 oz',
        speed: 'n/s',
        axle2axle: '62"',
        level: 'advanced',
        category: 'hunting',
        type: 'recurve',
        color: 'Dark Wood',
        url: 'https://martinarchery.com/traditional-bows/damon-howatt-scorpion-recurve-bow/#buy',
    },  
    {
        name: 'Mamba',
        imgSrc: './images/mamba.png',
        imgAlt: 'Mamba Recurve Bow',
        drawWeight: '35, 40, 45, 50, 55, 60, 65 lbs',
        drawLength: 'n/a',
        massWeight: '1 lb 14 oz',
        speed: 'n/a',
        axle2axle: '58"',
        level: 'advanced',
        category: 'hunting',
        type: 'recurve',
        color: 'Cherry Oak',
        url: 'https://martinarchery.com/traditional-bows/damon-howatt-mamba-recurve-bow/',
    },  
    {
        name: 'Freedom',
        imgSrc: './images/freedom.png',
        imgAlt: 'Freedom Recurve Bow',
        drawWeight: '25, 30, 35, 40, 45, 50, 55 lbs',
        drawLength: 'n/a',
        massWeight: '1 lb 12 oz',
        speed: 'n/a',
        axle2axle: '60"',
        level: 'beginner',
        category: 'hunting',
        type: 'recurve',
        color: 'Dark Wood',
        url: 'https://martinarchery.com/traditional-bows/damon-howatt-freedom-recurve-bow/',
    },  
    {
        name: 'Independence',
        imgSrc: './images/independence.png',
        imgAlt: 'Independence Recurve Bow',
        drawWeight: '25, 30, 35, 40, 45, 50, 55 lbs',
        drawLength: 'n/a',
        massWeight: '1 lb 12 oz',
        speed: 'n/a',
        axle2axle: '52"',
        level: 'beginner',
        category: 'hunting',
        type: 'recurve',
        color: 'Cherry Oak',
        url: 'https://martinarchery.com/traditional-bows/damon-howatt-independence-recurve-bow/',
    },  
    {
        name: 'Wolverine',
        imgSrc: './images/wolverine.png',
        imgAlt: 'Wolverine Recurve Bow',
        drawWeight: '40, 45, 50 lbs',
        drawLength: 'n/a',
        massWeight: 'n/a',
        speed: 'n/a',
        axle2axle: '62"',
        level: 'beginner',
        category: 'competition',
        type: 'recurve',
        color: 'Maple',
        url: 'https://beararchery.com/bows/wolverine-arb16240r',
    },  
    {
        name: 'Spyder Takedown',
        imgSrc: './images/spydertakedown.png',
        imgAlt: 'Spyder Takedown Recurve Bow',
        drawWeight: '20, 25, 29, 35, 40, 45, 50, 55, 60 lbs',
        drawLength: 'n/a',
        massWeight: 'n/a',
        speed: 'n/a',
        axle2axle: '62" ',
        level: 'intermediate',
        category: 'competition',
        type: 'recurve',
        color: 'White Oak, Dymond Wood, Padouk',
        url: 'https://www.southwestarcheryusa.com/collections/all-bows/products/southwest-archery-spyder-62-takedown-recurve-bow-parent-1?variant=217106546704',
    },  
    {
        name: 'Arcos Riser',
        imgSrc: './images/arcosriser.png',
        imgAlt: 'Arcos Riser Recurve Bow',
        drawWeight: '40, 45, 50, 55 lbs',
        drawLength: 'n/a',
        massWeight: '3 lbs',
        speed: 'n/a',
        axle2axle: '25" Riser Length',
        level: 'advanced',
        category: 'competition',
        type: 'recurve',
        color: 'Lava Red, Pitch Black, White Lightning, Electric Blue, Smoke Gray',
        url: 'https://hoyt.com/recurve-bows/arcos',
    },  
    {
        name: '',
        imgSrc: '',
        imgAlt: '',
        drawWeight: '',
        drawLength: '',
        massWeight: '',
        speed: '',
        axle2axle: '',
        level: '',
        category: '',
        type: '',
        color: '',
        url: '',
    },  
    {
        name: '',
        imgSrc: '',
        imgAlt: '',
        drawWeight: '',
        drawLength: '',
        massWeight: '',
        speed: '',
        axle2axle: '',
        level: '',
        category: '',
        type: '',
        color: '',
        url: '',
    },  
    {
        name: '',
        imgSrc: '',
        imgAlt: '',
        drawWeight: '',
        drawLength: '',
        massWeight: '',
        speed: '',
        axle2axle: '',
        level: '',
        category: '',
        type: '',
        color: '',
        url: '',
    },  
    {
        name: '',
        imgSrc: '',
        imgAlt: '',
        drawWeight: '',
        drawLength: '',
        massWeight: '',
        speed: '',
        axle2axle: '',
        level: '',
        category: '',
        type: '',
        color: '',
        url: '',
    },  


];

// level - beginner int or advaced
// category - competition or hunting
// type - compound or recurve bows
// {
//     name: '',
//     imgSrc: '',
//     imgAlt: '',
//     drawWeight: '',
//     drawLength: '',
//     massWeight: '',
//     speed: '',
//     axle2axle: '',
//     level: '',
//     category: '',
//     type: '',
//     color: '',
//     url: '',
// },